### ISSUE TITLE
Install only mode?

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#158]
I was hoping I could use tea to install software without starting a REPL or running a command. Right now, to avoid running the REPL I need to do this:

```
tea +pkg echo ""
```

It would be nice if I could bulk install software, like what brew bundle does.

One example use case that I've already bumped into is creating Docker containers (I saw the PSA, it will take me awhile to change my workflow completely). This is my [Dockerfile](https://github.com/magnusviri/pantry.magnusviri/blob/e0eeaeaf1e18c22bc908186179b878f22d4cd3cb/Dockerfile#L13).

**Comment by jhheider** [comment]
Definitely a worthy path for investigation. In its current form, `tea` will provide the same functionality, regardless of prior install status. So, the intent is that you can run `tea [+pkg...] command` and it will install _if needed_ or just link in otherwise the listed packages and run the command.

There will be a definite need to preinstall packages for e.g. airgapped systems, or if people want to use tea in their Dockerfiles and optimize order of operations. `echo ""` doesn't seem like the worst stop-gap measure in the world, but eventually it shouldn't be necessary.

If you want slightly more verbose and introspectable commands, I might default to something like `tea +python.org=3.x.y python --version`, so I can be sure I'm getting what I need.

**Comment by mxcl** [comment]
Yep, makes sense. We will get this, though as yet not sure of the shape.

The upcoming `tea/cmd` will help since people will be able to write commands to do just about anything that are then pluggable into tea. One such command will be `install` no doubt. Another could emulate `brew bundle`

There ofc, is @jhheider’s snippet to inject into the “command not found handler” and make `$ foo` run `tea -X foo` behind the scenes.

**Comment by magnusviri** [comment]
I hear this will be a community-added feature. I'll close this then.
