### ISSUE TITLE
FORK BOMB ACTIVATED

### ISSUE THREAD

**Issue by tnxz** [teaxyz/cli#306]
assuming `ln -s $(which tea) ~/.local/bin/git` to add a symlink `git` which invokes `tea git`, doesn't seem to work.

**Comment by jhheider** [comment]
Is ~/.local/bin in your $PATH? What happens when you call `git`, `~/.local/bin/git`, and `which tea`?

**Comment by tnxz** [comment]
yes, `~/.local/bin` is on path.
`~/.local/bin/git init` causes #308
`git init` - `/usr/bin/git`
`which tea` - `~/.tea/tea.xyz/v*/bin/tea`

**Comment by mxcl** [comment]
There must be a cycle between `tea` and a symlink to tea for this to occur. Let me try and figure it out.

**Comment by mxcl** [comment]
This is quite a mystery to me, what shell do you have @tnxz? can you give us the sanitized output of `env`? Thank you and sorry for this bug.

**Comment by tnxz** [comment]
wiped `tea` and did a clean install and the problem doesnt seem to occur anymore, not sure why

**Comment by tnxz** [comment]
now, its back again but this time with `cc` after `ln -s $(which tea) ~/.local/bin/cc`  `~/.local/bin` is in the PATH

shell - `zsh`
env -
```
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/0_/d7g53fyx473c04wzy2bs9ck40000gn/T/
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.8LDN4Q6OXo/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=447
TERM_SESSION_ID=051FB76A-ED79-4DC1-88D3-0380CE847326
SHELL=/bin/zsh
HOME=/Users/run
LOGNAME=run
USER=run
PATH=/Users/run/.tea/tea.xyz/v*/bin:/Users/run/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
SHLVL=1
PWD=/Users/run
OLDPWD=/Users/run
SHELL_SESSIONS_DISABLE=1
LESSHISTFILE=-
LSCOLORS=ExFxCxDxBxegedabagacad
CLICOLOR=1
EDITOR=nvim
LANG=en_US.UTF-8
_=/usr/bin/env

```

`~/.zshrc` only includes tea's magic script and nothing fancy
`~/.zprofile` just adding `~/.local/bin` to PATH

**Comment by mxcl** [comment]
I traced an instance of this bug to the binaries we provided via: 

```
curl -Lo tea https://tea.xyz/$(uname)/$(uname -m)
```

Because we compiled those separately and we were accidentally adding `./tea` to the hardcoded default args in the binary. Which meant any usage of `tea` would then call `tea`. Amazing bug really.

However this only affects the standalone generated URL via the above curl. And you used the installer yes?

**Comment by tnxz** [comment]
yes `sh <(curl tea.xyz)`

**Comment by mxcl** [comment]
Hoping 0.19.5 fixes it (update with `sh <(curl tea.xyz)`)

**Comment by mxcl** [comment]
I've traced an example of this bug to when the symlink is in the terminal’s *current directory*. Per chance is that your scenario?

**Comment by tnxz** [comment]
no

**Comment by mxcl** [comment]
Oh ok, this only happens with `cc` due to the way we try to translate `cc` to different things based on context. Sorry, I should have precisely followed your directions. I stupidly assumed it was a general bug.

**Comment by mxcl** [comment]
k fix coming today, however this still won’t work well since our `cc` package is a stub that resolves to llvm on linux and Xcode CLT on macOS.

This is because we built it to allow us to build packages and we hadn't thought further ahead than that.

I'll give it some thought as I would like it to be generally useful and enable Mac users to avoid the Xcode CLT.

For now you could do a two symlink approach of `cc` -> `clang` -> `tea`.

**Comment by mxcl** [comment]
`tea -S +tea.xyz/gx/cc` should update it once is merged and bottles uploaded https://github.com/teaxyz/pantry.core/pull/113
