### ISSUE TITLE
panic:Broken pipe (os error 32)

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#327]
----------------------------------------------------->> attachment begin
BrokenPipe: Broken pipe (os error 32)
    at async dump (file:///opt/tea.xyz/src/v0.19.6/src/app.dump.ts:54:17)
    at async file:///opt/tea.xyz/src/v0.19.6/src/app.ts:40:21
<<----------------------------------------------------- attachment end

This error occurred after running the script 

```sh
tea https://github.com/mfts/tea-demos/blob/feat/ai-commit-msg/ai-commit-msg/ai-commit-msg.sh
```

The error is related to [line 35](https://github.com/mfts/tea-demos/blob/feat/ai-commit-msg/ai-commit-msg/ai-commit-msg.sh#L35)

https://user-images.githubusercontent.com/4049052/213758534-f8ce80c9-0c1e-4bf5-8a5b-632c0217c29f.mov

tea 0.19.6

**Comment by mxcl** [comment]
Notably line 35 is pointless since you don't use python in the script itself.

---

All the same let’s try and figure out what is happening.

This suggest tea cannot write to stdout since nothing is using pipes in `app.dump.ts`. The part of the script this is happening in is: `source <(tea +python.org^3 --dry-run)`

It's hard to see what the problem is precisely.

**Comment by mfts** [comment]
hmm ok then line 35 is not what I need. I was under the impression it would add it to the repositories env kind of like adding the dependency to a dep table in the Readme and then stepping into the directory.

**Comment by mxcl** [comment]
What is “the repository” in this context?
