### ISSUE TITLE
`panic:cannot intersect: ^2 && ^3.7` when using python

### ISSUE THREAD

**Issue by Odilf** [teaxyz/cli#502]
I wanted to run an old python 2 script and tea seemed perfect for the job since I don't want to fuzz around with managing python versions. However, when I run `tea python^2` I get that error (if I do `tea python^2.7` I get `panic:cannot intersect: ^2.7 && ^3.7`. `tea python` just brings up python 3.11. 

I assume this is a bug because `tea node^16` for example works fine. It's also suspicious that it says it's not compatible with 3.7 since the last minor of 2 was 2.7 and 3 is up to 3.11. 

Is it just that it's not in the registry or something?

I'm on an M1 mac btw.

**Comment by mxcl** [comment]
This is because our pip pkg is considered a “companion” to python but we don't have a pip that can support python < 3.7.

An easy fix for now would be to stop pip having that requirement.

After that the problem is we don’t have a python 2 pkg. We tried but it was quite involved. I'll give it another go today.

**Comment by mxcl** [comment]
Solved with a hack.
