### ISSUE TITLE
question: npm_config_prefix is no longer set to npm installation bin path

### ISSUE THREAD

**Issue by anapsix** [teaxyz/cli#588]
I've noticed that `v0.26.4` removed (see https://github.com/teaxyz/cli/compare/v0.26.3...v0.26.4) setting the `npm_config_prefix`, which now defaults to `~/.local`. Which means that globally installed NPM package binaries / executables are now placed into `~/.local/bin`.

In `v0.26.3` it was possible to launch the NPM installed CLI tool (for example, `tea +npmjs.com^9.6.7 npm install -g nodemon`) with something like this: `tea +npmjs.com^9.6.7 nodemon`. In `v0.26.4` and beyond it is no longer possible, though `tea +npmjs.com^9.6.7 npx nodemon` can be used in place.
But wouldn't that present a problem when multiple versions of NPM are installed, yet same `npm_config_prefix` path is used by all the versions? As additional installs of the same NPM package, but using different NPM version, would end up overwriting each other.

Am I misunderstanding the issue? And is it a non-issue?

<details><summary>NPM prefix in 0.26.3 vs 0.26.4</summary>

```
# tea --version
tea 0.26.3
# tea npm --version
9.6.7
# tea npm prefix -g
/opt/tea/npmjs.com/v9.6.7
```
vs
```
# tea --version
tea 0.26.4
# tea npm --version
9.6.7
# tea npm prefix -g
/root/.local
```
</details>

**Comment by jhheider** [comment]
I _think_ it's a non-issue, since the installs aren't (generally) dependent on the version used to install them. And, in fact, I think most users expect to have the same packages installed, regardless of the version of npm.

I think if you install with a post-0.26.4 npm invocation, your execute invocation should also work, since they'll have been looking at the same ~/.local.

**Comment by mxcl** [comment]
We exchanged one bug for another.

* Before if you updated npm you lost all your global installs
* Now they don't work without tea.

We can fix the second with more hacks, I haven't the time RN tho as I'm knee deep in libtea.

**Comment by anapsix** [comment]
> I think if you install with a post-0.26.4 npm invocation, your execute invocation should also work, since they'll have been looking at the same ~/.local.

As long as the nodejs version is the same (or compatible). This brings up another point.. The npm is mostly used to resolve (and install) dependencies when installing packages. It relies on nodejs version itself. Would coupling npm packages with nodejs version by setting `npm_config_prefix` to tea's nodejs path make more sense? This way `tea +nodejs.org^${node_ver} ${npm_installed_bin}` would actually make sense?

**Comment by jhheider** [comment]
Then we get back the prior issue, where if you remove the node version, you lose all your packages. I agree that you can hit inconsistencies between module and engine versions, but I don't think that coupling them that closely is a great solution.

For non-global packages, obviously, this problem is contained to a single environment/directory. Global packages, _hopefully_ take care to be more compatible, more easily, but it isn't perfect to just throw our hands in the air and proclaim "whatever happens!" I've definitely had issues, before `tea`, where a node update would break a global package, so I'm not even sure that node/npm have solved this yet. But ideas are definitely always welcome.

**Comment by anapsix** [comment]
I see what you mean @jhheider. Short of sticking the npm packages into `~/.local/<node_ver>/bin` and sprinkling it all with symlinks for good measure 😆, there isn't much I can see we could do here

**Comment by jhheider** [comment]
as currently constituted, the best way to interact with the consumer system is the `runtime.env:` keys, so setting any particular node envvar that might make things more sane is definitely feasible. there's a lot of options, so plenty we _could_ consider; we'd just need to consider them. ;)

**Comment by mxcl** [comment]
The `node` not in `PATH` issue is fixed.

Regarding the separate issue of segmenting out `npm install -g` destinations based on `npm` version I think as a default `-g` means *global* meaning combined.

However I think making it possible to configure how this works in a general tea sense is not a bad idea. We were discussing this sort of thing here: https://github.com/orgs/teaxyz/discussions/391

Closing, but reopen if you think I am wrong or have misunderstood.
