### ISSUE TITLE
WSL2 not auto symlinking

### ISSUE THREAD

**Issue by vladdeSV** [teaxyz/cli#620]
On WSL2, no symlinks are created. No `~/.tea/.local/bin/` folder is created; I can only see `~/.tea/.local/tmp/`.

```sh
~ $ tea --version
tea 0.35.8
~ $ which node
~ $ node --version
v20.3.1
~ $ ls ~/.tea/.local/
tmp
```

**Comment by mxcl** [comment]
the symlinks are added when you install so probs it's that and you need to reinstall node.

**Comment by vladdeSV** [comment]
That does not happen. When I do these steps:
- completely remove tea (remove from .bashrc and `rm -rf ~/.tea`)
- `sh <(curl https://tea.xyz)` and install with magic
- open new shell and run `node --version`

no symlink is created.

![tea 620](https://github.com/teaxyz/cli/assets/7542961/68077e16-a640-4e92-97b1-e1c9532bfa92)

**Comment by felipecrs** [comment]
Is my understanding correct that https://github.com/denoland/deno/pull/17468 will address this admonition?

![image](https://github.com/teaxyz/cli/assets/29582865/976514b1-addd-4928-9e16-be7ddcbe5695)

If it is, the text may be a bit misleading. By platform, I understand Linux itself and not a limitation of Deno.

If it is not (i.e. Linux limitation), I wonder how [Volta](https://volta.sh/) works around it:

```console
❯ ls -la $(which node)
lrwxrwxrwx 1 felipecrs felipecrs 37 Oct 25  2022 /home/felipecrs/.volta/bin/node -> /home/felipecrs/.volta/bin/volta-shim
❯ node --version
v18.17.0
```

**Comment by mxcl** [comment]
Closing as we no longer do this, instead use `tea install`. Thanks for the report! LMK if our decision sucks etc!

**Comment by felipecrs** [comment]
To me, the biggest drawback of stubs vs symlinks is that symlinks can become outdated at any time, while stubs could not. I'd much prefer symlinks instead.

In my dotfiles repository, for example, it would be much simpler if I could simply add symlinks from `~/.local/bin/node` to `./tea` rather than having to invoke `tea install node` in a script. Like I do for Volta: https://github.com/felipecrs/dotfiles/blob/d9b125c4ad6d976e074b2c28d5f8ce2f7ec80516/home/dot_volta/bin/symlink_yarn.tmpl

**Comment by mxcl** [comment]
> To me, the biggest drawback of stubs vs symlinks is that stubs can become outdated at any time, while symlinks could not. I'd much prefer symlinks instead.

The stub can be changed to drop the version constraint. I don't think this should be the default operation since it makes it quite unlike any other `install` command. When installing things people expect stability. eg.

```
tea +node=20.1.2 -- node "$@"
```

Could become:

```
tea +node -- node "$@"
```

Thus using the latest version (that is installed). This is the same behavior as the symlinks were.

> I believe symlinks would be simpler for users by all means

I appreciate your feedback, but I really don't think most users would consider symlinks simpler than `tea install foo`.

---

Feel free to open a discussion about this. No decision we make is final, we just try to do what is best by our vision for this tool and our community. We could add symlinks back, they can be dangerous, but maybe that's a reasonable trade off.

**Comment by felipecrs** [comment]
> The stub can be changed to drop the version constraint. I don't think this should be the default operation since it makes it quite unlike any other `install` command—when installing things people expect stability—however we could add it as an option to the `install` command.

Sorry, that's not what I meant by "can become outdated". I meant, let's say:

- tea v1.0.0 creates stubs with `tea +node node "$@"`
- then, tea v1.0.1 creates stubs with `tea +node -- node "$@"`
- or, tea v1.1.0 creates stubs with something like `[[ -f ./package.json ]] && exec tea dev [...]`

Then stubs created with v1.0.0 would be kept outdated and would require an additional `tea install` command to fix them up.

**Comment by felipecrs** [comment]
> I appreciate your feedback, but I really don't think most users would consider symlinks simpler than tea install foo.

I'm sorry, but I did not mean that symlinks are simpler than `tea install foo`. In fact, I would expect `tea install foo` to create the symlinks for users, as opposed to stubs.

It meant that it is simpler when creating them manually, or when trying to understand how they work. I.e:

```bash
ln -s ./tea ~/.local/bin/node
```

As compared to:

```bash
printf '%s' '#!/bin/sh' 'exec tea node "${@}"' | tee ~/.local/bin/node
```

**Comment by felipecrs** [comment]
But I understand there are some limitations in this approach. Specifically, you cannot add the information of which package specifically is providing the command in case more than one does.

All that said, I think it's totally understandable if you decide to go with the stubs approach.

> We could add symlinks back, they can be dangerous, but maybe that's a reasonable trade off.

If it's just because of me, don't do it. Let's see what more people think about it. This is not dealbreaker for me either, I would not stop using tea because of that. I love tea!
