### ISSUE TITLE
1.0.0-alpha.3 relocatable?

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#731]
When I try to run git directly, I get a warning.

```
/Users/james/.tea/git-scm.org/v\*/bin/git clone https://github.com/teaxyz/setup.git
Cloning into 'setup'...
warning: templates not found in /opt/git-scm.org/v2.42.0/share/git-core/templates
```

**Comment by jhheider** [comment]
I believe that's because `git` bakes in paths at compile time. It's why we set runtime variables: https://github.com/teaxyz/pantry/blob/18c8b383b70e8b1b474ade952f7c8ec5abbace71/projects/git-scm.org/package.yml#L16-L19

Fortunately, just a warning, but that's the solution if you want to do it manually.

**Comment by mxcl** [comment]
`/Users/james/.tea/git-scm.org/v\*/bin/git` yeah running it directly like this means we cannot set the runtime env, which for git is necessary for it to find its templates. So… working as expected however I would prefer packages to not require runtime env for relocatable reasons. Often it is easiest so that is where we are at.

Reopen if misdiagnosed.
